version: "1"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodatabase"
    ports:
      - 27017:27017
  redisdb:
    image: redis:latest
    container_name: "redisdatabase"
    ports:
      - 6379:6379
  backendapp:
    image: tarea2:1.0
    container_name: "tarea2"
    ports:
      - 8080:8080
    links:
      - mongodb
      - redisdb